{"timestamp":"2020-02-22 13:48:29.522","username":"","log_level":"ERROR","service":"magic-system","pid":"1477","thread":"ThreadPoolTaskScheduler-1","class":"org.springframework.cloud.alibaba.nacos.discovery.NacosWatch","line_number":"171","stack_trace":"java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/service/list after all servers([116.62.142.9:8840]) tried: failed to req API:http://116.62.142.9:8840/nacos/v1/ns/service/list. code:500 msg: java.net.ConnectException: Network is unreachable (connect failed)\n\tat com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:380)\n\tat com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:346)\n\tat com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:294)\n\tat com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:276)\n\tat com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:252)\n\tat com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:525)\n\tat org.springframework.cloud.alibaba.nacos.discovery.NacosWatch.nacosServicesWatch(NacosWatch.java:127)\n\tat org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)\n\tat java.util.concurrent.FutureTask.runAndReset(FutureTask.java)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n","message":"Error watching Nacos Service change"}
